name: Build

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0       
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./Cloud1
          file: ./Cloud1/Dockerfile
          push: true
          load: false
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/cloud1:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/cloud1:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.VPN_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy file to remote machine
        run: |
          ssh ubuntu@${{ secrets.VPN_HOST }} 'mkdir -p cloud1-dep'  
          scp -o StrictHostKeyChecking=no deploy.sh ubuntu@${{ secrets.VPN_HOST }}:/home/ubuntu/cloud1-dep/deploy.sh
          ssh ubuntu@${{ secrets.VPN_HOST }} 'IMAGE_URL=${{ steps.login-ecr.outputs.registry }}/cloud1:${{ github.sha }} sh /home/ubuntu/cloud1-dep/deploy.sh'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
