name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Change dir
        run: |
          pwd
          ls -la
          cd Cloud1
          ls -la
          pwd           
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: Cloud1
          file: Dockerfile
          push: true
          load: false
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/cloud1:${{ github.ref_name }}
            ${{ steps.login-ecr.outputs.registry }}/cloud1:latest
      
